# Generated by Django 4.2.7 on 2025-08-17 15:51

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRuleSet',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('default_environment', models.CharField(blank=True, max_length=10)),
                ('default_product', models.CharField(blank=True, max_length=50)),
                ('default_work_type', models.CharField(blank=True, max_length=50)),
                ('required_approvals', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None)),
                ('prechecks', models.JSONField(blank=True, default=dict)),
                ('default_checklist', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='project',
            name='chk_proj_env_values',
        ),
        migrations.RemoveConstraint(
            model_name='project',
            name='chk_proj_status_values',
        ),
        migrations.RemoveConstraint(
            model_name='project',
            name='chk_proj_worktype_values',
        ),
        migrations.RemoveConstraint(
            model_name='project',
            name='chk_proj_fuse_values',
        ),
        migrations.RemoveConstraint(
            model_name='project',
            name='chk_proj_cert_values',
        ),
        migrations.RemoveConstraint(
            model_name='project',
            name='chk_proj_prod_requires_sre',
        ),
        migrations.RemoveIndex(
            model_name='technician',
            name='idx_tech_is_manager',
        ),
        migrations.RemoveIndex(
            model_name='technician',
            name='idx_tech_role',
        ),
        migrations.AlterField(
            model_name='project',
            name='app_server',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='database_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='db_server',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='environment',
            field=models.CharField(choices=[('test', 'Test'), ('prod', 'Production')], max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='product',
            field=models.CharField(choices=[('GRF', 'GRF'), ('GRM', 'GRM'), ('GFM', 'GFM'), ('Clinibase CI', 'Clinibase CI'), ('GRH', 'GRH'), ('eClinibase', 'eClinibase'), ('SIurge', 'SIurge'), ('Sicheld', 'Sicheld'), ('Med Echo', 'Med Echo'), ('I-CLSC', 'I-CLSC'), ('RadImage', 'RadImage')], max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='rollback_planned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('on_hold', 'En pause'), ('cancelled', 'Annulé')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='work_type',
            field=models.CharField(choices=[('Migration', 'Migration'), ('Mise a niveau', 'Mise à niveau'), ('Rehaussement', 'Rehaussement'), ('Demenagement', 'Déménagement'), ('Copie de BD', 'Copie de BD'), ('Installation poste de Support', 'Installation poste de Support')], default='Migration', max_length=50),
        ),
        migrations.AlterField(
            model_name='technician',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='technician',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['client_name'], name='idx_proj_client'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['date'], name='idx_proj_date'),
        ),
        migrations.AddField(
            model_name='projectruleset',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulesets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='ruleset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='crm_app.projectruleset'),
        ),
        migrations.AddIndex(
            model_name='projectruleset',
            index=models.Index(fields=['owner'], name='idx_rules_owner'),
        ),
        migrations.AddIndex(
            model_name='projectruleset',
            index=models.Index(fields=['default_environment', 'default_product'], name='idx_rules_env_prod'),
        ),
        migrations.AddIndex(
            model_name='projectruleset',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='idx_rules_tags_gin'),
        ),
        migrations.AddConstraint(
            model_name='projectruleset',
            constraint=models.CheckConstraint(check=models.Q(('name', ''), _negated=True), name='chk_rules_name_not_empty'),
        ),
    ]
