# Generated by Django 4.2.7 on 2025-08-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0006_checklisttemplate_checklistitemnote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='role',
            field=models.CharField(default='Technicien', max_length=500),
        ),
    ]
