# Generated by Django 4.2.7 on 2025-08-18 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm_app', '0007_alter_technician_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Personne à qui ce projet est assigné', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='autres_produits_verifier',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='autres_ressources_client_cc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='bd',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='bi_a_valider',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_tech_client_cc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_tech_client_to',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='courriel_confirmation_client',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='equipe_dev_ajouter',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='equipe_integration_ajouter',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='etablissement',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='gestionnaire_projet',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='note_importante',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='projet_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='responsable_travaux',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='serveur_bd',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='tables_m34',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='taches_installations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='travaux_a_faire',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='version_actuelle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='version_cible',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
