# Generated by Django 4.2.7 on 2025-08-18 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0008_project_assigned_to_project_autres_produits_verifier_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='idx_proj_status_tech_created',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='idx_proj_env_prod',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='idx_proj_client_prod_status',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='idx_proj_client',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='idx_proj_date',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='idx_proj_creator_recent',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='idx_proj_tech_recent',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='idx_proj_phases',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='idx_proj_geo_region',
        ),
        migrations.RemoveField(
            model_name='project',
            name='bd',
        ),
        migrations.RemoveField(
            model_name='project',
            name='projet_code',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ruleset',
        ),
        migrations.RemoveField(
            model_name='project',
            name='serveur_bd',
        ),
    ]
