# Generated by Django 4.2.7 on 2025-08-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0009_remove_project_idx_proj_status_tech_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklisttemplate',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='error_impact',
        ),
        migrations.RemoveField(
            model_name='project',
            name='error_solution',
        ),
        migrations.RemoveField(
            model_name='project',
            name='etablissement',
        ),
        migrations.RemoveField(
            model_name='project',
            name='execution_completed_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='execution_phase',
        ),
        migrations.RemoveField(
            model_name='project',
            name='execution_started_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='project',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='project',
            name='preparation_completed_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='preparation_phase',
        ),
        migrations.RemoveField(
            model_name='project',
            name='preparation_started_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='rollback_planned',
        ),
        migrations.RemoveField(
            model_name='project',
            name='site_city',
        ),
        migrations.RemoveField(
            model_name='project',
            name='site_country',
        ),
        migrations.RemoveField(
            model_name='project',
            name='site_region',
        ),
        migrations.RemoveField(
            model_name='project',
            name='timeline_data',
        ),
        migrations.RemoveField(
            model_name='project',
            name='validation_completed_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='validation_phase',
        ),
        migrations.RemoveField(
            model_name='project',
            name='validation_started_at',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='location',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='title',
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='json_payload',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='project',
            name='app_server',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='database_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='db_server',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='product',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='ProjectRuleSet',
        ),
    ]
