# Generated by Django 4.2.7 on 2025-08-21 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0016_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
