# Generated by Django 4.2.11 on 2025-08-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0017_delete_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="coordination_board",
            field=models.TextField(blank=True, default=""),
        ),
    ]
