# Generated by Django 4.2.11 on 2025-08-22 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0018_alter_project_coordination_board"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="version_actuelle",
        ),
        migrations.RemoveField(
            model_name="project",
            name="version_cible",
        ),
    ]
