# Generated by Django 4.2.11 on 2025-08-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0019_remove_project_version_actuelle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="version_actuelle",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="project",
            name="version_cible",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
