# Generated by Django 4.2.11 on 2025-08-22 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0020_project_version_actuelle_project_version_cible"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="execution_phase",
            new_name="production_phase",
        ),
        migrations.RemoveField(
            model_name="project",
            name="validation_phase",
        ),
    ]
