# Generated by Django 4.2.11 on 2025-08-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0021_rename_execution_phase_project_production_phase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="application_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
