# Generated by Django 4.2.11 on 2025-08-22 17:33

import crm_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0022_project_application_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="coordination_board",
            field=models.ImageField(
                blank=True, null=True, upload_to=crm_app.models.coordination_board_path
            ),
        ),
    ]
