# Generated by Django 4.2.11 on 2025-08-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0023_alter_project_coordination_board"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_number",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
