# Generated by Django 4.2.11 on 2025-08-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0024_alter_project_project_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
