# Generated by Django 4.2.11 on 2025-08-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0025_alter_project_project_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="preparation_phase_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="preparation_phase_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="production_phase_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="production_phase_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
