# Generated by Django 4.2.11 on 2025-09-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0026_project_preparation_phase_completed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_opened",
            field=models.BooleanField(default=False),
        ),
    ]
